language: ruby
rvm: 2.2.3
cache:
  - bundler
  - apt
addons:
  postgresql: '9.6'
before_install:
  - sudo apt-get update --qq
  - sudo apt-get -qq postgresql-server-dev-9.6 libpq-dev
before_script:
  - psql -c 'CREATE DATABASE slowfood_v1_test;' -U postgres
script:
  - bundle exec rspec
  - bundle exec cucumber
